#!/bin/bash
git mv docs/init.html docs/index.html
sed -i 's/init.html/index.html/g' docs/*.html
git add docs
git commit -m 'Auto-update docs.'
doc_sha=$(git ls-tree -d HEAD docs | awk '{print $3}')
new_commit=$(echo "Auto-update docs." | git commit-tree $doc_sha -p refs/heads/gh-pages)
git update-ref refs/heads/gh-pages $new_commit
